Improve response code handling
pulumiverse/pulumi-purrl pull request #75
Opened 2023-04-15 19:19 UTC by necaris

This PR:
 - renames the `response_codes` and `delete_response_codes` parameters to make them more self-explanatory
 - adds the HTTP response code to the outputs, to aid in debugging API calls during development

2023-04-15 19:30 UTC, dirien reviewed
Hi @necaris,

thanks for your contribution! Can you keep the old properties please and mark them as deprecated so we can slowly delete them and avoid any harsh braking changes!

Also I would ask to split the PR into two: Add new properties and return value for better debugging!

Thanks!

2023-04-16 16:19 UTC, necaris commented
@dirien thank you for the feedback! I've kept the response code field in this PR and moved the renames to #79 , as suggested!

2023-04-25 17:04 UTC, dirien requested changes
Hi @necaris,

thanks for the contribution.

I left some comments for changes.

2023-04-25 17:04 UTC, dirien commented on provider/pkg/provider/purrl/purrl.go
> +	insecureSkipVerify *bool, caCert, cert, key *string) (*string, *string, error) {
Can you change the first return type to `*int`

2023-04-25 17:04 UTC, dirien commented on provider/pkg/provider/purrl/purrl.go
> +		return strPtr(string(resp.StatusCode)), nil, fmt.Errorf("error reading response body: %v", readErr)
Create a new function:

```go
func intPtr(i int) *int {
	return &i
}
```

and change to `return intPtr(resp.StatusCode), ...

2023-04-25 17:04 UTC, dirien commented on provider/pkg/provider/purrl/purrl.go
> +		return strPtr(string(resp.StatusCode)), nil, fmt.Errorf("error calling API endpoint: %v", err)
Create a new function:

```go
func intPtr(i int) *int {
	return &i
}
```

and change to `return intPtr(resp.StatusCode), ...

2023-04-25 17:04 UTC, dirien commented on provider/pkg/provider/purrl/purrl.go
> +		return strPtr(string(resp.StatusCode)), nil, errors.New("response code not in list of expected response codes")
Create a new function:

```go
func intPtr(i int) *int {
	return &i
}
```

and change to `return intPtr(resp.StatusCode), ...

2023-04-25 17:04 UTC, dirien commented on provider/pkg/provider/purrl/purrl.go
> +	return strPtr(string(resp.StatusCode)), strPtr(string(respBody)), nil
Create a new function:

```go
func intPtr(i int) *int {
	return &i
}
```

and change to `return intPtr(resp.StatusCode), ...

2023-04-26 02:32 UTC, necaris commented
@dirien thank you for the review! Changed the first return value to an int as suggested.

2023-04-28 07:57 UTC, dirien approved these changes
LGTM! Many thanks @necaris for the contributon!

2023-04-28 08:01 UTC, merged

2023-04-28 08:22 UTC, dirien commented
And it is released! https://github.com/pulumiverse/pulumi-purrl/releases/tag/v0.4.0