Rename `ResponseCodes` to `ExpectedResponseCodes`
pulumiverse/pulumi-purrl pull request #79
Opened 2023-04-16 16:11 UTC by necaris

Add `ExpectedResponseCodes` and `ExpectedDeleteResponseCodes` inputs, which are more self-explanatory, and mark `ResponseCodes` and `DeleteResponseCodes` as deprecated in field annotations. Also add a `Check()` implementation that ensures only one of the inputs is set, and sets the new field appropriately so we can use the new field consistently elsewhere in the code.

Supersedes #75, from feedback.

2023-04-28 13:55 UTC, dirien requested changes
Hi @necaris,

can you rebase the PR please? Then I can start the review!

2023-05-04 11:42 UTC, dirien requested changes
hey @necaris,

thanks for rebasing this. I left a little review and after this we are ready to merge this!

2023-05-04 11:42 UTC, dirien commented on provider/cmd/pulumi-resource-purrl/schema.json
> +                    "description": "The expected response code(s) for deletion. Deprecated -- use `expectedDeleteResponseCodes` instead.",
Hi @necaris,

can you use `deprecationMessage` instead?

see  https://www.pulumi.com/docs/guides/pulumi-packages/schema/#property

2023-05-04 11:42 UTC, dirien commented on provider/cmd/pulumi-resource-purrl/schema.json
> +                    "description": "The expected response code(s). Deprecated -- use `expectedResponseCodes` instead.",
Hi @necaris,

can you use `deprecationMessage` instead?

see  https://www.pulumi.com/docs/guides/pulumi-packages/schema/#property

2023-05-04 11:42 UTC, dirien commented on provider/cmd/pulumi-resource-purrl/schema.json
> +                    "description": "The expected response code(s) for deletion. Deprecated -- use `expectedDeleteResponseCodes` instead.",
Hi @necaris,

can you use `deprecationMessage` instead?

see  https://www.pulumi.com/docs/guides/pulumi-packages/schema/#property

2023-05-04 11:42 UTC, dirien commented on provider/cmd/pulumi-resource-purrl/schema.json
> +                    "description": "The expected response code(s). Deprecated -- use `expectedResponseCodes` instead.",
Hi @necaris,

can you use `deprecationMessage` instead?

see  https://www.pulumi.com/docs/guides/pulumi-packages/schema/#property

2023-05-08 12:46 UTC, dirien reviewed
Hi @necaris,

thanks for the rebase. I tested the new code with following example:

```go
func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {
		purrlCommand, err := purrl.NewPurrl(ctx, "httpbin", &purrl.PurrlArgs{
			Url:  pulumi.String("https://httpbin.org/get"),
			Name: pulumi.String("httpbin"),
			ExpectedResponseCodes: pulumi.StringArray{
				pulumi.String("200"),
			},
			Method: pulumi.String("GET"),
			Headers: pulumi.StringMap{
				"test": pulumi.String("test"),
			},
			DeleteMethod: pulumi.String("DELETE"),
			DeleteUrl:    pulumi.String("https://httpbin.org/delete"),
			ExpectedDeleteResponseCodes: pulumi.StringArray{
				pulumi.String("200"),
			},
		})
		if err != nil {
			return err
		}
		ctx.Export("actual response code", purrlCommand.ResponseCode)
		return nil
	})
}
```

And I get following message:

```bash
View in Browser (Ctrl+O): https://app.pulumi.com/dirien/purrl-go/dev/previews/475953b4-4093-49b8-9b8f-f98cbf73725c

     Type                  Name          Plan     Info
     pulumi:pulumi:Stack   purrl-go-dev           2 messages
     └─ purrl:index:Purrl  httpbin                1 error


Diagnostics:
  purrl:index:Purrl (httpbin):
    error: at least one of deleteResponseCodes or expectedDeleteResponseCodes must be provided

  pulumi:pulumi:Stack (purrl-go-dev):
```

I think the `Check` function is not proper working.

2023-05-08 12:55 UTC, necaris commented
Thanks @dirien for the review! Let me look at it.

2023-05-21 10:14 UTC, dirien commented
Hi @necaris,

do you need any additional feedback from me for this?

2023-06-11 09:43 UTC, dirien commented
Hey @necaris,

closing this PR for now. Feel free to open a new one if necessary!

Thanks!

2023-06-11 09:43 UTC, closed without merging